---
id: ListHeaders
name: ListHeaders
full: List headers parsing library
description: A library that parses Mailing List Headers as defined in RFC 2369 & RFC 2919.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_ListHeaders
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 2.0.0alpha4
  api: 2.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/mail: ^3
      horde/translation: ^3
      horde/util: ^3
  optional:
    composer:
      horde/mime: ^3
      horde/test: ^3
